[package]
name = "flock"
version = "0.1.0"
authors = ["michael <mhoward@sportingindex.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
magic-crypt = "3.1.5"